# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='project',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='upload_data',
            new_name='upload_date',
        ),
    ]
