# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0002_auto_20170729_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_name_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
