# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_remove_data_file_name_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene', models.CharField(blank=True, max_length=200)),
                ('protein', models.CharField(blank=True, max_length=200)),
                ('compound', models.CharField(blank=True, max_length=200)),
                ('compound_id', models.CharField(blank=True, max_length=200)),
                ('p_value', models.FloatField()),
                ('treated_control_fold_change', models.FloatField()),
                ('significant_flag', models.BooleanField()),
                ('exp_method', models.CharField(max_length=200)),
                ('species_type', models.CharField(max_length=200)),
                ('sample_id', models.CharField(max_length=200)),
                ('data_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='measurements',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Measurement'),
        ),
    ]
