# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_auto_20170730_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='measurements',
        ),
        migrations.AddField(
            model_name='dataset',
            name='measurements',
            field=models.ManyToManyField(to='gui.Measurement'),
        ),
    ]
