# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0008_auto_20170730_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='all_data',
            field=models.CharField(blank=True, max_length=2000000),
        ),
    ]
