# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0009_data_all_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='measurement',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
