# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0010_auto_20170812_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='data',
            name='times',
        ),
    ]
