# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 18:32
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0012_remove_data_all_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='data',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
    ]
