# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0013_data_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrichmentOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200)),
                ('database', models.CharField(blank=True, max_length=200)),
                ('data', picklefield.fields.PickledObjectField(blank=True, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='modality',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name='data',
            name='time_points',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
