# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 21:46
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0014_auto_20170818_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='all_measured',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='data',
            name='sig_measured',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='data',
            name='sig_uni',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='data',
            name='uni_measured',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False),
        ),
    ]
